import express from "express";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
const app = express();
const PORT = process.env.PORT || 10001; // default to 10001 locally to avoid local port conflicts

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ✅ Resolve client build output. Try common output locations and pick the first that exists.
const candidatePaths = [
  path.join(__dirname, "../client/dist"), // when client built into client/dist
  path.join(__dirname, "../dist/client/dist"), // when build output ends up under dist/client/dist
  path.join(__dirname, "../..", "client", "dist"), // alternate nested layout
  path.join(__dirname, "../../dist"), // fallback
];

let clientBuildPath = candidatePaths.find((p) => fs.existsSync(path.join(p, "index.html")));
if (!clientBuildPath) {
  clientBuildPath = path.join(__dirname, "../client/dist");
}

console.log(`Serving client from: ${clientBuildPath}`);
console.log(`Server will listen on port: ${PORT}`);

// Parse JSON bodies for API routes
app.use(express.json());

// Minimal API: analyze-text (mock implementation)
app.post('/api/analyze-text', (req, res) => {
  const { content, contentType } = req.body || {};

  // Very small validation (server is intentionally minimal here)
  if (!content || typeof content !== 'string' || content.trim().length < 10) {
    return res.status(400).json({ error: 'Content must be at least 10 characters' });
  }

  // Return a mock AnalysisReport matching src/shared/types.ts shape
  const mockReport = {
    credibilityScore: 72,
    analysis: `Mock analysis for content type ${contentType || 'text'}.`,
    flags: ['Possible bias detected', 'Unsupported claim'],
    recommendations: ['Check original sources', 'Verify author credentials'],
    reasoning: 'This is a mocked response generated by the server for development.',
    sources: [],
  };

  return res.json(mockReport);
});

app.use(express.static(clientBuildPath));

// Serve index.html for any request not handled by static middleware.
// Using `app.use` without a path avoids path-to-regexp parsing issues in some environments.
app.use((req, res) => {
  res.sendFile(path.join(clientBuildPath, "index.html"));
});

app.listen(PORT, () => {
  console.log(`✅ Server running on port ${PORT}`);
});
